name: basic pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

jobs:
  pipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: npm install backend
        run: |
          echo "hello firneds XD" > .env
          cat .env
          ls -la
          npm i
        working-directory: ./server
        
      - name: npm install frontend
        run: npm i
        working-directory: ./client
      
      - name: Lint backend
        run: |
          ls -la
          cat .env
          npm run lint
        working-directory: ./server
        
      - name: Lint frontend
        run: npm run eslint
        working-directory: ./client
        
      - name: Unit test backend
        run: 
          npm test
        working-directory: ./server
        
      - name: Unit test frontend
        run: npm test
        working-directory: ./client
        
      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:test
          wait-on: http://localhost:3000
          working-directory: ./client
          
      - name: build
        run: npm run build:full
        working-directory: ./server
          
      - name: heroku deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          working-directory: ./server
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flano-final-01235"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://flano-final-01235.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Slack post
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
